### ISSUE TITLE
Interop tests

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-libp2p-ipfs-nodejs#15]
As discussed on Aug 15 Sprint Call, let's come up with a set of recipes to test js-libp2p against go-libp2p. Here is a start:
- Swarm + TCP
- Swarm + TCP + SPDY
- Swarm + TCP + SPDY + Identify (ability to reuse connections)
- Swarm + TCP + SPDY + Identify + SECIO

@whyrusleeping sounds doable? We might not be able to do some depending how modular go-libp2p is right now.

**Comment by diasdavid** [comment]
🛎 @whyrusleeping any update on this?

**Comment by dignifiedquire** [comment]
@whyrusleeping @diasdavid what's the state of this?
