### ISSUE TITLE
[multiplex] muxedConns pool is not updated after a swarm.close

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js-libp2p-ipfs-nodejs#58]
Reproduce by running `npm run test:muxer:multiplex`

Seems that `multiplex.destroy` is not effectively doing the same as [`spdy.destroyStreams`](https://github.com/libp2p/js-libp2p-spdy/blob/master/src/muxer.js#L61)

**Comment by VictorBjelkholm** [comment]
Fixed in https://github.com/libp2p/js-libp2p-swarm/pull/163
